# Generated by Django 4.0.4 on 2022-04-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='threats',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
