# Generated by Django 4.0.4 on 2022-04-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whale',
            old_name='life_expectancy',
            new_name='lifespan',
        ),
    ]
