# Generated by Django 4.0.4 on 2022-04-21 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
        ('whales', '0002_rename_life_expectancy_whale_lifespan'),
    ]

    operations = [
        migrations.AddField(
            model_name='whale',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='environment.environment'),
        ),
    ]
