# Generated by Django 4.0.4 on 2022-04-21 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_environment_threats'),
        ('whales', '0004_whale_supporting_environment_alter_whale_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whale',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name', to='environment.environment'),
        ),
        migrations.AlterField(
            model_name='whale',
            name='supporting_environment',
            field=models.ManyToManyField(related_name='supported', to='environment.environment'),
        ),
    ]
