# Generated by Django 4.0.4 on 2022-04-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_remove_environment_threats'),
        ('whales', '0005_alter_whale_environment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whale',
            name='supporting_environment',
            field=models.ManyToManyField(blank=True, to='environment.environment'),
        ),
    ]
