# Generated by Django 4.0.4 on 2022-04-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0001_initial'),
        ('whales', '0006_alter_whale_supporting_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='whale',
            name='threats',
            field=models.ManyToManyField(blank=True, to='threats.threats'),
        ),
    ]
