# Generated by Django 4.0.4 on 2022-04-23 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0002_threats_created'),
        ('whales', '0007_whale_threats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whale',
            name='threats',
        ),
        migrations.AddField(
            model_name='whale',
            name='threat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name', to='threats.threats'),
        ),
    ]
