# Generated by Django 4.0.4 on 2022-04-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_remove_environment_threats'),
        ('threats', '0003_alter_threats_description'),
        ('whales', '0008_remove_whale_threats_whale_threat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whale',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whales', to='environment.environment'),
        ),
        migrations.RemoveField(
            model_name='whale',
            name='threat',
        ),
        migrations.AddField(
            model_name='whale',
            name='threat',
            field=models.ManyToManyField(blank=True, to='threats.threats'),
        ),
    ]
