# Generated by Django 4.0.4 on 2022-04-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whales', '0010_remove_whale_supporting_environment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whale',
            name='threat',
        ),
    ]
