# Generated by Django 4.0.4 on 2022-04-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_remove_environment_threats'),
        ('threats', '0003_alter_threats_description'),
        ('whales', '0011_remove_whale_threat'),
    ]

    operations = [
        migrations.AddField(
            model_name='whale',
            name='supporting_environment',
            field=models.ManyToManyField(blank=True, to='environment.environment'),
        ),
        migrations.AddField(
            model_name='whale',
            name='threat',
            field=models.ManyToManyField(blank=True, to='threats.threats'),
        ),
    ]
