# Generated by Django 4.0.4 on 2022-04-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_remove_environment_threats'),
        ('whales', '0013_remove_whale_supporting_environment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whale',
            name='supporting_environment',
            field=models.ManyToManyField(blank=True, to='environment.environment'),
        ),
    ]
